/* SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2026 Shi Jimmy
 */
/* config.h for the vendored libosmocore conv.c (Android / host build).
 * Generated by hand: only the macros conv.c tests are provided. */
#ifndef TETRA_ANDROID_LIBOSMOCORE_CONFIG_H
#define TETRA_ANDROID_LIBOSMOCORE_CONFIG_H

#if !defined(_WIN32)
#  define HAVE_ALLOCA_H 1
#  define HAVE_PTHREAD 1
#endif

#endif
